const ticketActionType = {
    ADD_TICKET: 'ADD_TICKET',
    REMOVE_TICKET: 'REMOVE_TICKET',
    ADD_SELECTED_TICKET: 'ADD_SELECTED_TICKET',
    ADD_COMMENTARY: 'ADD_COMMENTARY',
    ADD_LENDING: 'ADD_LENDING'

}

export default ticketActionType;